services:
  - type: web
    name: proxy-checker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PORT
        fromService:
          type: web
          name: proxy-checker
          property: port
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: proxy-checker-disk
      mountPath: /opt/render/project/src
      sizeGB: 1